# Generated by Django 3.0.6 on 2020-05-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('model_no', models.CharField(blank=True, max_length=255, null=True)),
                ('ram', models.IntegerField(help_text='GB')),
                ('rom', models.IntegerField(help_text='GB')),
                ('screen', models.FloatField(help_text='inch')),
                ('front_camera', models.IntegerField(help_text='MegaPixels')),
                ('rear_camera', models.IntegerField(help_text='MegaPixels')),
            ],
        ),
    ]
