# Generated by Django 3.0.6 on 2020-05-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('age', models.IntegerField()),
                ('category', models.CharField(help_text='Football Cricket etc', max_length=255)),
            ],
        ),
    ]
