# Generated by Django 3.0.6 on 2020-05-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewset', '0002_blog_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='thumbnail',
        ),
    ]
